language: clojure

jobs:
  include:
  - stage: test
    script: lein test
  - stage: deploy
    script: bash script/codecov.sh
  - script: echo "Starting deployment job"
    deploy:
      provider: script
      script: lein deploy clojars
      on:
        branch: master
